workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Patch device_apps plugin
        script: |
          echo "Patching device_apps plugin to include namespace..."
          GRADLE_FILE="$HOME/.pub-cache/hosted/pub.dev/device_apps-2.2.0/android/build.gradle"
          if [ -f "$GRADLE_FILE" ]; then
            sed -i '' '/android {/a\
                namespace "com.deviceapps"
            ' "$GRADLE_FILE"
          else
            echo "Gradle file not found: $GRADLE_FILE"
            exit 1
          fi
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
